name: Static Site CI

on:
  push:
    branches: [ main ]

jobs:
  verify-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List project files
        run: ls -R
